name: Update Light State

on:
  workflow_dispatch:
    inputs:
      new_state:
        description: 'Switch state'
        required: true
        default: 'OFF'

jobs:
  update-state:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update state.json
        run: echo "{ \"state\": \"${{ github.event.inputs.new_state }}\" }" > state.json

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update state to ${{ github.event.inputs.new_state }}"
